# pylint: disable=C0103,R0801
# Generated by Django 4.2.16 on 2024-10-17 11:24

import django.db.models.deletion
import ovinc_client.core.models
import ovinc_client.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorConfig",
            fields=[
                (
                    "id",
                    ovinc_client.core.models.UniqIDField(
                        default=ovinc_client.core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_type", models.CharField(choices=[("HTTP", "HTTP")], max_length=32, verbose_name="Check Type")),
                ("check_interval", models.IntegerField(default=60, verbose_name="Check Interval (s)")),
                ("check_timeout", models.IntegerField(default=10, verbose_name="Check Timeout (s)")),
                ("check_retry", models.IntegerField(default=3, verbose_name="Check Retry")),
                ("is_enabled", models.BooleanField(db_index=True, default=True, verbose_name="Is Enabled")),
                ("last_check_time", models.BigIntegerField(default=0, verbose_name="Last Schedule Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                (
                    "http_method",
                    models.CharField(
                        blank=True, choices=[("GET", "GET")], max_length=32, null=True, verbose_name="HTTP Method"
                    ),
                ),
                ("http_url", models.TextField(blank=True, null=True, verbose_name="HTTP URL")),
                ("http_headers", models.JSONField(blank=True, null=True, verbose_name="HTTP Headers")),
                ("http_follow_redirect", models.BooleanField(blank=True, null=True, verbose_name="Follow Redirect")),
                (
                    "http_check_status_code",
                    models.IntegerField(blank=True, null=True, verbose_name="HTTP Success Status Code"),
                ),
                (
                    "created_by",
                    ovinc_client.core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_monitor_config",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor_config",
                        to="service.service",
                        verbose_name="Service",
                    ),
                ),
                (
                    "updated_by",
                    ovinc_client.core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_monitor_config",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitor Config",
                "verbose_name_plural": "Monitor Config",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceStatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.BigIntegerField(verbose_name="Timestamp(s)")),
                ("datetime", models.DateTimeField(verbose_name="Time")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Online"), (1, "Offline"), (2, "Timeout"), (3, "Unknown")], verbose_name="Status"
                    ),
                ),
                ("status_msg", models.TextField(blank=True, null=True, verbose_name="Status Message")),
                (
                    "duration",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=13, null=True, verbose_name="Duration(ms)"
                    ),
                ),
                ("extra", models.JSONField(blank=True, null=True, verbose_name="Extra")),
                (
                    "service",
                    ovinc_client.core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_dot",
                        to="service.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Status",
                "verbose_name_plural": "Service Status",
                "ordering": ["-id"],
                "index_together": {("service", "timestamp")},
            },
        ),
    ]
